/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao;

import Modelo.Calcular;
import Modelo.Triangulo;

/**
 *
 * @author 1072419878
 */
public class FrmTriangulo extends javax.swing.JFrame {

    /**
     * Creates new form FrmTriangulo
     */
    public FrmTriangulo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        JLBase = new javax.swing.JLabel();
        JTFA = new javax.swing.JTextField();
        JLOp = new javax.swing.JLabel();
        JLResultado = new javax.swing.JLabel();
        JLResult = new javax.swing.JLabel();
        JbCalcular = new javax.swing.JButton();
        JbLimpar = new javax.swing.JButton();
        JbFechar = new javax.swing.JButton();
        JCCaixa = new javax.swing.JComboBox<>();
        JLAltura = new javax.swing.JLabel();
        JTFB = new javax.swing.JTextField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculo da area de um triangulo");

        JLBase.setText("Valo A");

        JTFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFAActionPerformed(evt);
            }
        });

        JLOp.setText("Operações");

        JLResultado.setText("Resultado");

        JLResult.setText("0.0");

        JbCalcular.setText("Calcular");
        JbCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCalcularActionPerformed(evt);
            }
        });

        JbLimpar.setText("Limpar");
        JbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbLimparActionPerformed(evt);
            }
        });

        JbFechar.setText("Fechar");
        JbFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbFecharActionPerformed(evt);
            }
        });

        JCCaixa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soma", "Subtração", "Vezes", "Divisão" }));
        JCCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCCaixaActionPerformed(evt);
            }
        });

        JLAltura.setText("Valor B");

        JTFB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JCCaixa, 0, 260, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLBase)
                            .addComponent(JTFA, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLOp)
                            .addComponent(JLResultado)
                            .addComponent(JLResult)
                            .addComponent(JLAltura)
                            .addComponent(JTFB, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JbCalcular)
                            .addComponent(JbLimpar))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JbFechar)
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(JLBase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JbCalcular))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(JbLimpar)
                        .addGap(34, 34, 34)
                        .addComponent(JbFechar))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JLAltura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTFB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLOp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JCCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(JLResultado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLResult)))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCalcularActionPerformed
        // TODO add your handling code here:
        Calcular cal1 = new Calcular();
        cal1.setA(Double.parseDouble(JTFA.getText()));
        cal1.setB(Double.parseDouble(JTFB.getText()));

        String option = JCCaixa.getSelectedItem() + "";
        switch (option) {
            case "Soma":
                JLResult.setText(cal1.getA() + cal1.getB() + "");
                break;
                case "Subtração":
                JLResult.setText(cal1.getA() - cal1.getB() + "");
                break;
                case "Vezes":
                JLResult.setText(cal1.getA() * cal1.getB() + "");
                break;
                case "Divisão":
                JLResult.setText(cal1.getA() / cal1.getB() + "");
                break;
        }
    }//GEN-LAST:event_JbCalcularActionPerformed

    private void JTFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFAActionPerformed

    private void JbFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbFecharActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_JbFecharActionPerformed

    private void JbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbLimparActionPerformed
        // TODO add your handling code here:
        JTFA.setText("");
        JTFB.setText("");
        JLResult.setText("0.0");
    }//GEN-LAST:event_JbLimparActionPerformed

    private void JCCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCCaixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCCaixaActionPerformed

    private void JTFBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTriangulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JCCaixa;
    private javax.swing.JLabel JLAltura;
    private javax.swing.JLabel JLBase;
    private javax.swing.JLabel JLOp;
    private javax.swing.JLabel JLResult;
    private javax.swing.JLabel JLResultado;
    private javax.swing.JTextField JTFA;
    private javax.swing.JTextField JTFB;
    private javax.swing.JButton JbCalcular;
    private javax.swing.JButton JbFechar;
    private javax.swing.JButton JbLimpar;
    private javax.swing.JComboBox<String> jComboBox1;
    // End of variables declaration//GEN-END:variables
}
